name: Prepare Terragrunt

on: [push]

jobs:
  job_tg:
    name: Job prepare tg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.26.0
      - name: Interact with Terragrunt
        run: terragrunt --version
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4
      - name: Interact with Terraform
        run: terraform --version

